name: fast_courier
description: Fast Courier App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#    google_maps_flutter: ^0.0.3+3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/user.png
    - assets/car.png
    - assets/mandiri.png
    - assets/bca.png
    - assets/bni.png
    - assets/motor.png
    - assets/courier.png
    - assets/facebook.png
    - assets/google.png


  fonts:
    - family: Montserrat
      fonts :
        - asset: assets/Montserrat-Black.ttf
        - asset: assets/Montserrat-BlackItalic.ttf
        - asset: assets/Montserrat-Bold.ttf
#        - asset: assets/Montserrat-BoldItalic.ttf
#        - asset: assets/Montserrat-ExtraBold.ttf
#        - asset: assets/Montserrat-ExtraBoldItalic.ttf
#        - asset: assets/Montserrat-ExtraLight.ttf
#        - asset: assets/Montserrat-ExtraLightItalic.ttf
#        - asset: assets/Montserrat-Italic.ttf
#        - asset: assets/Montserrat-Light.ttf
#        - asset: assets/Montserrat-LightItalic.ttf
#        - asset: assets/Montserrat-Medium.ttf
#        - asset: assets/Montserrat-MediumItalic.ttf
#        - asset: assets/Montserrat-Regular.ttf
#        - asset: assets/Montserrat-SemiBold.ttf
#        - asset: assets/Montserrat-SemiBoldItalic.ttf
#        - asset: assets/Montserrat-Thin.ttf
#        - asset: assets/Montserrat-ThinItalic.ttf

    - family: Quicksand
      fonts:
        - asset: assets/Quicksand-Bold.ttf
        - asset: assets/Quicksand-Light.ttf
        - asset: assets/Quicksand-Medium.ttf
        - asset: assets/Quicksand-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
